### ISSUE TITLE
How to load user customized compose file?

### ISSUE THREAD

**Issue by magichowl** [fcitx/fcitx#147]
I've installed fcitx 4.2.8.1 and I can input Unicode characters with accents under input method *Keyboard - English (US)* of fcitx, say
á, à, ...

But I want more, for example greek letter, say ⍺. 

I use ~/.XCompose dowload from http://github.org/kragen/xcompose and managed to load .XCompose file by im-swicth -s default-xim -z zh_CN.
But in that situation, I can't input chinese.

Therefore, could anyone teach me how to add .XCompose for fcitx?

**Comment by wengxt** [comment]
Fcitx git now make use of xkbcommon to process compose, this should be fixed.

**Comment by magichowl** [comment]
libxkbcommon 0.5.0 is required, but there is not deb but source code, 

Though I installed libxkbcommon 0.5.0, but  "cmake " fcitx always fails with the error: 

found unsuitable version 0.4.1(/usr/lib/x86_64-linux-gnu/libxkbcommon.so).

I know my new library installed in "/usr/local/lib", but can't replace the old one, 

Would you mind  giving some hints?

**Comment by wengxt** [comment]
try
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
before running cmake.

**Comment by magichowl** [comment]
error still the same 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find XKBCommon: Found unsuitable version "0.4.1", but required is
  at least "0.5.0" (found /usr/lib/x86_64-linux-gnu/libxkbcommon.so)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindXKBCommon.cmake:29 (find_package_handle_standard_args)
  CMakeLists.txt:74 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/pan/Documents/fcitx-git/build/CMakeFiles/CMakeOutput.log".
See also "/home/pan/Documents/fcitx-git/build/CMakeFiles/CMakeError.log".

**Comment by magichowl** [comment]
I find a dirty workaround: 

# find_package(XKBCommon 0.5.0 REQUIRED COMPONENTS XKBCommon)
set(XKBCommon_INCLUDE_DIRS "/usr/local/include/xkbcommon")
set (XKBCommon_LIBRARY "/usr/local/lib/libxkbcommon.so")

**Comment by magichowl** [comment]
change the requirement from 0.5.0 to 0.4.1 is not succeeded either:

CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_reset':
fcitximcontext-gio.c:(.text+0x2381): undefined reference to `xkb_compose_state_reset'
collect2: error: ld returned 1 exit status
src/frontend/gtk2/CMakeFiles/im-fcitx.dir/build.make:114: recipe for target 'src/frontend/gtk2/im-fcitx.so' failed
make[2]: *** [src/frontend/gtk2/im-fcitx.so] Error 1
CMakeFiles/Makefile2:7823: recipe for target 'src/frontend/gtk2/CMakeFiles/im-fcitx.dir/all' failed
make[1]: *** [src/frontend/gtk2/CMakeFiles/im-fcitx.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wengxt** [comment]
You need to remove CMakeCache.txt, and then export PKG_CONFIG_PATH and
re-run cmake.

**Comment by magichowl** [comment]
do you know what is going on when I "make"

[ 86%] Building C object src/frontend/gtk2/CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o
Linking C shared module im-fcitx.so
CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_init':
fcitximcontext-gio.c:(.text+0x903): undefined reference to `xkb_compose_table_new_from_locale'
fcitximcontext-gio.c:(.text+0xab3): undefined reference to `xkb_compose_state_new'
CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_finalize':
fcitximcontext-gio.c:(.text+0xb5a): undefined reference to `xkb_compose_state_unref'
CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_filter_keypress_fallback':
fcitximcontext-gio.c:(.text+0xe0d): undefined reference to `xkb_compose_state_feed'
fcitximcontext-gio.c:(.text+0xe3e): undefined reference to `xkb_compose_state_get_status'
fcitximcontext-gio.c:(.text+0xe92): undefined reference to `xkb_compose_state_get_utf8'
fcitximcontext-gio.c:(.text+0xea1): undefined reference to `xkb_compose_state_reset'
fcitximcontext-gio.c:(.text+0xee0): undefined reference to `xkb_compose_state_reset'
CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_reset':
fcitximcontext-gio.c:(.text+0x2381): undefined reference to `xkb_compose_state_reset'
collect2: error: ld returned 1 exit status
src/frontend/gtk2/CMakeFiles/im-fcitx.dir/build.make:114: recipe for target 'src/frontend/gtk2/im-fcitx.so' failed
make[2]: *** [src/frontend/gtk2/im-fcitx.so] Error 1
CMakeFiles/Makefile2:8128: recipe for target 'src/frontend/gtk2/CMakeFiles/im-fcitx.dir/all' failed
make[1]: *** [src/frontend/gtk2/CMakeFiles/im-fcitx.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by magichowl** [comment]
there are two errors if I use "make -i", 

```
...
Linking C shared module im-fcitx.so
CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_init':
fcitximcontext-gio.c:(.text+0x903): undefined reference to `xkb_compose_table_new_from_locale'
fcitximcontext-gio.c:(.text+0xab3): undefined reference to `xkb_compose_state_new'
CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_finalize':
fcitximcontext-gio.c:(.text+0xb5a): undefined reference to `xkb_compose_state_unref'
CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_filter_keypress_fallback':
fcitximcontext-gio.c:(.text+0xe0d): undefined reference to `xkb_compose_state_feed'
fcitximcontext-gio.c:(.text+0xe3e): undefined reference to `xkb_compose_state_get_status'
fcitximcontext-gio.c:(.text+0xe92): undefined reference to `xkb_compose_state_get_utf8'
fcitximcontext-gio.c:(.text+0xea1): undefined reference to `xkb_compose_state_reset'
fcitximcontext-gio.c:(.text+0xee0): undefined reference to `xkb_compose_state_reset'
CMakeFiles/im-fcitx.dir/fcitximcontext-gio.c.o: In function `fcitx_im_context_reset':
fcitximcontext-gio.c:(.text+0x2381): undefined reference to `xkb_compose_state_reset'
collect2: error: ld returned 1 exit status
[ 86%] Built target im-fcitx
[ 86%] Generating moc_qfcitxinputcontext.cxx
Scanning dependencies of target qtim-fcitx
[ 86%] Building CXX object src/frontend/qt/CMakeFiles/qtim-fcitx.dir/qfcitxinputcontextplugin.cpp.o
[ 87%] Building CXX object src/frontend/qt/CMakeFiles/qtim-fcitx.dir/qfcitxinputcontext.cpp.o
[ 87%] Building CXX object src/frontend/qt/CMakeFiles/qtim-fcitx.dir/moc_qfcitxinputcontext.cxx.o
Linking CXX shared module qtim-fcitx.so
CMakeFiles/qtim-fcitx.dir/qfcitxinputcontext.cpp.o: In function `QFcitxInputContext::QFcitxInputContext()':
qfcitxinputcontext.cpp:(.text+0x310): undefined reference to `xkb_compose_table_new_from_locale'
qfcitxinputcontext.cpp:(.text+0x360): undefined reference to `xkb_compose_state_new'
CMakeFiles/qtim-fcitx.dir/qfcitxinputcontext.cpp.o: In function `QFcitxInputContext::reset()':
qfcitxinputcontext.cpp:(.text+0xac1): undefined reference to `xkb_compose_state_reset'
CMakeFiles/qtim-fcitx.dir/qfcitxinputcontext.cpp.o: In function `QFcitxInputContext::processCompose(unsigned int, unsigned int, _FcitxKeyEventType)':
qfcitxinputcontext.cpp:(.text+0x3ae6): undefined reference to `xkb_compose_state_feed'
qfcitxinputcontext.cpp:(.text+0x3b05): undefined reference to `xkb_compose_state_get_status'
qfcitxinputcontext.cpp:(.text+0x3b47): undefined reference to `xkb_compose_state_get_utf8'
qfcitxinputcontext.cpp:(.text+0x3b56): undefined reference to `xkb_compose_state_reset'
qfcitxinputcontext.cpp:(.text+0x3ba7): undefined reference to `xkb_compose_state_reset'
CMakeFiles/qtim-fcitx.dir/qfcitxinputcontext.cpp.o: In function `XkbComposeTableDeleter::cleanup(xkb_compose_table*)':
qfcitxinputcontext.cpp:(.text._ZN22XkbComposeTableDeleter7cleanupEP17xkb_compose_table[_ZN22XkbComposeTableDeleter7cleanupEP17xkb_compose_table]+0x1b): undefined reference to `xkb_compose_table_unref'
CMakeFiles/qtim-fcitx.dir/qfcitxinputcontext.cpp.o: In function `XkbComposeStateDeleter::cleanup(xkb_compose_state*)':
qfcitxinputcontext.cpp:(.text._ZN22XkbComposeStateDeleter7cleanupEP17xkb_compose_state[_ZN22XkbComposeStateDeleter7cleanupEP17xkb_compose_state]+0x1b): undefined reference to `xkb_compose_state_unref'
collect2: error: ld returned 1 exit status
[ 87%] Built target qtim-fcitx
...
```
Thanks in advance.

**Comment by magichowl** [comment]
built it successfully, seems managed to use compose by  using keyboard English (US, international with dead keys),
It seems all I need to customize "xkbcommon-keysyms.h", but it is less readable than .XCompose file from http://github.org/kragen/xcompose 

E.g. in "xkbcommon-keysyms.h",
```
#define XKB_KEY_Greek_alpha                   0x07e1  /* U+03B1 GREEK SMALL LETTER ALPHA */
```
But I still don´t know how to insert  '⍺'.
